export interface Country {
  alpha3: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { alpha3: 'AFG', name: 'Afghanistan' },
  { alpha3: 'ALB', name: 'Albania' },
  { alpha3: 'DZA', name: 'Algeria' },
  { alpha3: 'AND', name: 'Andorra' },
  { alpha3: 'AGO', name: 'Angola' },
  { alpha3: 'ATG', name: 'Antigua and Barbuda' },
  { alpha3: 'ARG', name: 'Argentina' },
  { alpha3: 'ARM', name: 'Armenia' },
  { alpha3: 'AUS', name: 'Australia' },
  { alpha3: 'AUT', name: 'Austria' },
  { alpha3: 'AZE', name: 'Azerbaijan' },
  { alpha3: 'BHS', name: 'Bahamas' },
  { alpha3: 'BHR', name: 'Bahrain' },
  { alpha3: 'BGD', name: 'Bangladesh' },
  { alpha3: 'BRB', name: 'Barbados' },
  { alpha3: 'BLR', name: 'Belarus' },
  { alpha3: 'BEL', name: 'Belgium' },
  { alpha3: 'BLZ', name: 'Belize' },
  { alpha3: 'BEN', name: 'Benin' },
  { alpha3: 'BTN', name: 'Bhutan' },
  { alpha3: 'BOL', name: 'Bolivia' },
  { alpha3: 'BIH', name: 'Bosnia and Herzegovina' },
  { alpha3: 'BWA', name: 'Botswana' },
  { alpha3: 'BRA', name: 'Brazil' },
  { alpha3: 'BRN', name: 'Brunei' },
  { alpha3: 'BGR', name: 'Bulgaria' },
  { alpha3: 'BFA', name: 'Burkina Faso' },
  { alpha3: 'BDI', name: 'Burundi' },
  { alpha3: 'CPV', name: 'Cabo Verde' },
  { alpha3: 'KHM', name: 'Cambodia' },
  { alpha3: 'CMR', name: 'Cameroon' },
  { alpha3: 'CAN', name: 'Canada' },
  { alpha3: 'CAF', name: 'Central African Republic' },
  { alpha3: 'TCD', name: 'Chad' },
  { alpha3: 'CHL', name: 'Chile' },
  { alpha3: 'CHN', name: 'China' },
  { alpha3: 'COL', name: 'Colombia' },
  { alpha3: 'COM', name: 'Comoros' },
  { alpha3: 'COD', name: 'Congo (DRC)' },
  { alpha3: 'COG', name: 'Congo (Republic)' },
  { alpha3: 'CRI', name: 'Costa Rica' },
  { alpha3: 'HRV', name: 'Croatia' },
  { alpha3: 'CUB', name: 'Cuba' },
  { alpha3: 'CYP', name: 'Cyprus' },
  { alpha3: 'CZE', name: 'Czech Republic' },
  { alpha3: 'DNK', name: 'Denmark' },
  { alpha3: 'DJI', name: 'Djibouti' },
  { alpha3: 'DOM', name: 'Dominican Republic' },
  { alpha3: 'ECU', name: 'Ecuador' },
  { alpha3: 'EGY', name: 'Egypt' },
  { alpha3: 'SLV', name: 'El Salvador' },
  { alpha3: 'GNQ', name: 'Equatorial Guinea' },
  { alpha3: 'ERI', name: 'Eritrea' },
  { alpha3: 'EST', name: 'Estonia' },
  { alpha3: 'SWZ', name: 'Eswatini' },
  { alpha3: 'ETH', name: 'Ethiopia' },
  { alpha3: 'FJI', name: 'Fiji' },
  { alpha3: 'FIN', name: 'Finland' },
  { alpha3: 'FRA', name: 'France' },
  { alpha3: 'GAB', name: 'Gabon' },
  { alpha3: 'GMB', name: 'Gambia' },
  { alpha3: 'GEO', name: 'Georgia' },
  { alpha3: 'DEU', name: 'Germany' },
  { alpha3: 'GHA', name: 'Ghana' },
  { alpha3: 'GRC', name: 'Greece' },
  { alpha3: 'GRD', name: 'Grenada' },
  { alpha3: 'GTM', name: 'Guatemala' },
  { alpha3: 'GIN', name: 'Guinea' },
  { alpha3: 'GNB', name: 'Guinea-Bissau' },
  { alpha3: 'GUY', name: 'Guyana' },
  { alpha3: 'HTI', name: 'Haiti' },
  { alpha3: 'HND', name: 'Honduras' },
  { alpha3: 'HUN', name: 'Hungary' },
  { alpha3: 'ISL', name: 'Iceland' },
  { alpha3: 'IND', name: 'India' },
  { alpha3: 'IDN', name: 'Indonesia' },
  { alpha3: 'IRN', name: 'Iran' },
  { alpha3: 'IRQ', name: 'Iraq' },
  { alpha3: 'IRL', name: 'Ireland' },
  { alpha3: 'ISR', name: 'Israel' },
  { alpha3: 'ITA', name: 'Italy' },
  { alpha3: 'JAM', name: 'Jamaica' },
  { alpha3: 'JPN', name: 'Japan' },
  { alpha3: 'JOR', name: 'Jordan' },
  { alpha3: 'KAZ', name: 'Kazakhstan' },
  { alpha3: 'KEN', name: 'Kenya' },
  { alpha3: 'KIR', name: 'Kiribati' },
  { alpha3: 'PRK', name: 'Korea (North)' },
  { alpha3: 'KOR', name: 'Korea (South)' },
  { alpha3: 'KWT', name: 'Kuwait' },
  { alpha3: 'KGZ', name: 'Kyrgyzstan' },
  { alpha3: 'LAO', name: 'Laos' },
  { alpha3: 'LVA', name: 'Latvia' },
  { alpha3: 'LBN', name: 'Lebanon' },
  { alpha3: 'LSO', name: 'Lesotho' },
  { alpha3: 'LBR', name: 'Liberia' },
  { alpha3: 'LBY', name: 'Libya' },
  { alpha3: 'LIE', name: 'Liechtenstein' },
  { alpha3: 'LTU', name: 'Lithuania' },
  { alpha3: 'LUX', name: 'Luxembourg' },
  { alpha3: 'MDG', name: 'Madagascar' },
  { alpha3: 'MWI', name: 'Malawi' },
  { alpha3: 'MYS', name: 'Malaysia' },
  { alpha3: 'MDV', name: 'Maldives' },
  { alpha3: 'MLI', name: 'Mali' },
  { alpha3: 'MLT', name: 'Malta' },
  { alpha3: 'MHL', name: 'Marshall Islands' },
  { alpha3: 'MRT', name: 'Mauritania' },
  { alpha3: 'MUS', name: 'Mauritius' },
  { alpha3: 'MEX', name: 'Mexico' },
  { alpha3: 'FSM', name: 'Micronesia' },
  { alpha3: 'MDA', name: 'Moldova' },
  { alpha3: 'MCO', name: 'Monaco' },
  { alpha3: 'MNG', name: 'Mongolia' },
  { alpha3: 'MNE', name: 'Montenegro' },
  { alpha3: 'MAR', name: 'Morocco' },
  { alpha3: 'MOZ', name: 'Mozambique' },
  { alpha3: 'MMR', name: 'Myanmar' },
  { alpha3: 'NAM', name: 'Namibia' },
  { alpha3: 'NRU', name: 'Nauru' },
  { alpha3: 'NPL', name: 'Nepal' },
  { alpha3: 'NLD', name: 'Netherlands' },
  { alpha3: 'NZL', name: 'New Zealand' },
  { alpha3: 'NIC', name: 'Nicaragua' },
  { alpha3: 'NER', name: 'Niger' },
  { alpha3: 'NGA', name: 'Nigeria' },
  { alpha3: 'MKD', name: 'North Macedonia' },
  { alpha3: 'NOR', name: 'Norway' },
  { alpha3: 'OMN', name: 'Oman' },
  { alpha3: 'PAK', name: 'Pakistan' },
  { alpha3: 'PLW', name: 'Palau' },
  { alpha3: 'PAN', name: 'Panama' },
  { alpha3: 'PNG', name: 'Papua New Guinea' },
  { alpha3: 'PRY', name: 'Paraguay' },
  { alpha3: 'PER', name: 'Peru' },
  { alpha3: 'PHL', name: 'Philippines' },
  { alpha3: 'POL', name: 'Poland' },
  { alpha3: 'PRT', name: 'Portugal' },
  { alpha3: 'QAT', name: 'Qatar' },
  { alpha3: 'ROU', name: 'Romania' },
  { alpha3: 'RUS', name: 'Russia' },
  { alpha3: 'RWA', name: 'Rwanda' },
  { alpha3: 'KNA', name: 'Saint Kitts and Nevis' },
  { alpha3: 'LCA', name: 'Saint Lucia' },
  { alpha3: 'VCT', name: 'Saint Vincent and the Grenadines' },
  { alpha3: 'WSM', name: 'Samoa' },
  { alpha3: 'SMR', name: 'San Marino' },
  { alpha3: 'STP', name: 'Sao Tome and Principe' },
  { alpha3: 'SAU', name: 'Saudi Arabia' },
  { alpha3: 'SEN', name: 'Senegal' },
  { alpha3: 'SRB', name: 'Serbia' },
  { alpha3: 'SYC', name: 'Seychelles' },
  { alpha3: 'SLE', name: 'Sierra Leone' },
  { alpha3: 'SGP', name: 'Singapore' },
  { alpha3: 'SVK', name: 'Slovakia' },
  { alpha3: 'SVN', name: 'Slovenia' },
  { alpha3: 'SLB', name: 'Solomon Islands' },
  { alpha3: 'SOM', name: 'Somalia' },
  { alpha3: 'ZAF', name: 'South Africa' },
  { alpha3: 'SSD', name: 'South Sudan' },
  { alpha3: 'ESP', name: 'Spain' },
  { alpha3: 'LKA', name: 'Sri Lanka' },
  { alpha3: 'SDN', name: 'Sudan' },
  { alpha3: 'SUR', name: 'Suriname' },
  { alpha3: 'SWE', name: 'Sweden' },
  { alpha3: 'CHE', name: 'Switzerland' },
  { alpha3: 'SYR', name: 'Syria' },
  { alpha3: 'TWN', name: 'Taiwan' },
  { alpha3: 'TJK', name: 'Tajikistan' },
  { alpha3: 'TZA', name: 'Tanzania' },
  { alpha3: 'THA', name: 'Thailand' },
  { alpha3: 'TLS', name: 'Timor-Leste' },
  { alpha3: 'TGO', name: 'Togo' },
  { alpha3: 'TON', name: 'Tonga' },
  { alpha3: 'TTO', name: 'Trinidad and Tobago' },
  { alpha3: 'TUN', name: 'Tunisia' },
  { alpha3: 'TUR', name: 'Turkey' },
  { alpha3: 'TKM', name: 'Turkmenistan' },
  { alpha3: 'TUV', name: 'Tuvalu' },
  { alpha3: 'UGA', name: 'Uganda' },
  { alpha3: 'UKR', name: 'Ukraine' },
  { alpha3: 'ARE', name: 'United Arab Emirates' },
  { alpha3: 'GBR', name: 'United Kingdom' },
  { alpha3: 'USA', name: 'United States' },
  { alpha3: 'URY', name: 'Uruguay' },
  { alpha3: 'UZB', name: 'Uzbekistan' },
  { alpha3: 'VUT', name: 'Vanuatu' },
  { alpha3: 'VEN', name: 'Venezuela' },
  { alpha3: 'VNM', name: 'Vietnam' },
  { alpha3: 'YEM', name: 'Yemen' },
  { alpha3: 'ZMB', name: 'Zambia' },
  { alpha3: 'ZWE', name: 'Zimbabwe' },
];

// Build lookup maps for fast resolution
const byAlpha3 = new Map(COUNTRIES.map((c) => [c.alpha3.toUpperCase(), c]));
const byName = new Map(COUNTRIES.map((c) => [c.name.toLowerCase(), c]));

/**
 * Resolve a raw string (alpha-3 code or full name) to a Country.
 * Returns undefined if no match.
 */
export function resolveCountry(raw: string): Country | undefined {
  const trimmed = raw.trim();
  return byAlpha3.get(trimmed.toUpperCase()) ?? byName.get(trimmed.toLowerCase());
}
